#!/usr/bin/env bash

## Set GTK Themes, Icons, Cursor and Fonts

THEME='Gruvbox-Material-Dark'
ICONS='Papirus-Dark'
FONT='Caskaydia Cove Nerd Font 10'
CURSOR='Sweet'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes () {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
}

apply_themes
