#!/usr/bin/env bash

## launch wofi with alt config

CONFIG="$HOME/.config/sway/wofi/config"
STYLE="$HOME/.config/sway/wofi/style.css"

if [[ ! `pidof wofi` ]]; then
	wofi --show drun --prompt 'Search...' --conf ${CONFIG} --style ${STYLE}
else
	pkill wofi
fi
