#!/usr/bin/env bash

## Autostart Programs
# WLR-portals need this part
#dbus-update-activation-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river

# Kill already running process
_ps=(waybar mako)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -9 ${_prs}
	fi
done

if ! pgrep -x "polkit-gnome-authentication-agent-1" >/dev/null; then
    /usr/libexec/polkit-gnome-authentication-agent-1 &
fi


# Set wallpaper
#~/.config/river/scripts/wallpaper &

# Apply themes
~/.config/river/scripts/gtkthemes &

# Lauch notification daemon (mako)
~/.config/river/scripts/notifications &

# Lauch statusbar (waybar)
~/.config/river/scripts/statusbar &

# Start network manager applet
nm-applet --indicator &
