#!/bin/sh

$HOME/.config/river/autostart
$HOME/.config/river/options
$HOME/.config/river/keymap
$HOME/.config/river/rivertile
$HOME/.config/river/scripts/*
#$HOME/.config/river/scripts/statusbar
#$HOME/.config/river/script/wallpaper
