#!/bin/sh

touchpad=pointer-1267-12632-ELAN050A:01_04F3:3158_Touchpad

# Enable or disable the tap functionality of the input device.
riverctl input $touchpad tap enabled

# Enable tap-and-drag functionality of the input device.
riverctl input $touchpad drag enabled

# Set the pointer acceleration profile of the input device.
riverctl input $touchpad accel-profile none

# Set the pointer acceleration factor of the input device. Needs a float between -1.0 and 1.0.
riverctl input $touchpad pointer-accel 0.3

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Set background color
riverctl background-color 0x282828

# Enabled server side decorations
riverctl rule-add ssd

# Autofocus to spesific output by cursor
riverctl focus-follows-cursor disabled

# RULES
riverctl rule-add -app-id Pinentry-gtk float
riverctl rule-add -app-id xdg-desktop-portal-gtk float
riverctl rule-add -app-id nm-connection-editor float
riverctl rule-add -app-id com.usebottles.bottles csd
riverctl rule-add -app-id wpsoffice csd
riverctl rule-add -app-id foot-float float
riverctl rule-add -app-id alacritty-float float

# Make certain views start floating
riverctl float-filter-add app-id float
riverctl float-filter-add app-id 'pavucontrol'
riverctl float-filter-add app-id 'Timeshift-gtk'
riverctl float-filter-add app-id 'pavucontrol'
riverctl float-filter-add app-id 'nm-connection-editor'
riverctl float-filter-add app-id 'nwg-look'
riverctl float-filter-add app-id 'valent'
riverctl float-filter-add app-id 'file-roller'
riverctl float-filter-add app-id 'GParted'
riverctl float-filter-add app-id 'ristretto'
riverctl float-filter-add title "popup title with spaces"
riverctl float-filter-add title "Open File"
riverctl float-filter-add title "File Operation Progress"
riverctl float-filter-add title "Preferences"
riverctl float-filter-add title "dialog"
riverctl float-filter-add title "Picture-in-Picture"
riverctl float-filter-add title "bubble"
riverctl float-filter-add title "task_dialog"
riverctl float-filter-add title "menu"
riverctl float-filter-add title "Confirm to replace files"
riverctl float-filter-add title "foot-float"
