#!/usr/bin/env bash

## Set GTK Themes, Icons, Cursor and Fonts

THEME='Gruvbox-Material-Dark'
ICONS='Gruvbox-Material-Dark'
FONT='Cid Mono Nerd Font 12'
CURSOR='breeze_cursors'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes () {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
}

apply_themes
