#!/usr/bin/env bash

## launch waybar with alt config

CONFIG="$HOME/.config/niri/waybar_top/config"
STYLE="$HOME/.config/niri/waybar_top/style.css"

if [[ ! `pidof waybar` ]]; then
	waybar --bar main-bar --log-level error --config ${CONFIG} --style ${STYLE}
fi
